---
- name: Create group node_exporter
  group:
    name: node_exporter
    state: present
    system: true

- name: Create user node_exporter
  user:
    name: node_exporter
    group: node_exporter
    comment: Node Exporter
    create_home: false
    password_lock: true
    shell: /sbin/nologin
    system: true

- name: Download Node exporter version {{ node_exporter_version }}
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
    owner: node_exporter
    group: node_exporter
    checksum: sha256:https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/sha256sums.txt
    mode: 0600

- name: Extract Node exporter version {{ node_exporter_version }}
  unarchive:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true
    owner: node_exporter
    group: node_exporter
    mode: 0600

- name: Copy node_exporter to /usr/local/bin
  copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: true
    owner: node_exporter
    group: node_exporter
    mode: 0700
  notify: restart node_exporter

- name: Copy systemd service to server
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  notify: systemctl daemon-reload

- name: Enable and start node_exporter service
  systemd:
    name: node_exporter
    daemon_reload: true
    enabled: true
    state: started
