---
# handlers file for ansible-node-exporter
- name: systemctl daemon-reload
  systemd:
    daemon_reload: true

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
