---
# handlers file for ansible-node-exporter
- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
