FROM debian:jessie

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ansible \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
