FROM debian:stretch

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ansible \
    systemd \
    python \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
