FROM ubuntu:bionic

RUN apt-get update && apt-get install -y software-properties-common systemd && rm -rf /var/lib/apt/lists/*

RUN apt-add-repository -y ppa:ansible/ansible && apt-get update && apt-get install -y \
    ansible \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/bin/systemd"]
